version: '3.8'

services:
  user-db:
    image: postgres:16-alpine
    container_name: alertbus-user-db
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USER} -d ${USER_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  bus-db:
    image: postgres:16-alpine
    container_name: alertbus-bus-db
    environment:
      POSTGRES_DB: ${BUS_DB_NAME}
      POSTGRES_USER: ${BUS_DB_USER}
      POSTGRES_PASSWORD: ${BUS_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - bus_db_data:/var/lib/postgresql/data

  route-db:
    image: postgres:16-alpine
    container_name: alertbus-route-db
    environment:
      POSTGRES_DB: ${ROUTE_DB_NAME}
      POSTGRES_USER: ${ROUTE_DB_USER}
      POSTGRES_PASSWORD: ${ROUTE_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - route_db_data:/var/lib/postgresql/data

  trip-db:
    image: postgres:16-alpine
    container_name: alertbus-trip-db
    environment:
      POSTGRES_DB: ${TRIP_DB_NAME}
      POSTGRES_USER: ${TRIP_DB_USER}
      POSTGRES_PASSWORD: ${TRIP_DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - trip_db_data:/var/lib/postgresql/data



volumes:
  user_db_data:
  bus_db_data:
  route_db_data:
  trip_db_data: