server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      #  configuração global de CORD para aceitar requisições do front
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

            # mapeamento dos microserviços
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**, /auth/**

        - id: bus-service
          uri: http://localhost:8082
          predicates:
            - Path=/buses/**, /routes/**

        - id: route-service
          uri: http://localhost:8083
          predicates:
              - Path=/routes/**