server:
  port: 8084

spring:
  application:
    name: trip-service

  datasource:
    url: jdbc:postgresql://localhost:5435/trip_db
    username: ${TRIP_DB_USER}
    password: ${TRIP_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration